### ISSUE TITLE
线程问题

### ISSUE THREAD

**Issue by lvtanxi** [Rayhahah/EasyHttp#6]
mTvTest.setText(t.body()?.string())
这种直接报错。
还有不太方便转成自己的实体类，内置了parser好像没效果

**Comment by Rayhahah** [comment]
Parser目前还没做，只套了个空壳

**Comment by Rayhahah** [comment]
你说的线程问题，在Demo里面也实验了没什么问题啊

**Comment by lvtanxi** [comment]
t.body()?.string()是一个网络操作，放在主线程，肯定报错的，我运行的RX那个方法。

**Comment by Rayhahah** [comment]
最新版本已经修复了
